language: python
matrix:
    include:
        - python: 2.7
          env: TOXENV=py27-18
        - python: 2.7
          env: TOXENV=py27-110
        - python: 2.7
          env: TOXENV=py27-111
        - python: 3.3
          dist: precise
          env: TOXENV=py33-18
        - python: 3.4
          env: TOXENV=py34-18
        - python: 3.4
          env: TOXENV=py34-110
        - python: 3.4
          env: TOXENV=py34-111
        - python: 3.5
          env: TOXENV=py35-18
        - python: 3.5
          env: TOXENV=py35-110
        - python: 3.5
          env: TOXENV=py35-111
        - python: 3.6
          env: TOXENV=py36-111
        - python: pypy
          env: TOXENV=pypy-18
        - python: pypy
          env: TOXENV=pypy-110
        - python: pypy
          env: TOXENV=pypy-111
        - python: 2.7
          env: TOXENV=docs
        - python: 2.7
          env: TOXENV=flake8
before_install:
  - sudo apt-get -q -y update

  # The following three lines is a fix for travis CI, since it wouldn't be
  # able to install the dependencies correctly.
  # See: https://github.com/travis-ci/travis-ci/issues/2683
  - sudo apt-get remove -q -y binutils gdal-bin libproj-dev libgeos-c1
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable

  # Required to install Pillow
  - sudo apt-get -q -y install build-essential
  # GIS requirements.
  - sudo apt-get -q -y install binutils gdal-bin libproj-dev libgeos-c1
install:
  - pip install pip wheel
  - pip install tox
script:
  - tox -e $TOXENV
notifications:
  irc:
    channels:
      - "irc.freenode.org#django-floppyforms"
    on_success: change
    on_failure: always
deploy:
  provider: pypi
  user: gremu
  password:
    secure: HAgxb7ebUfIQSfcxtjKoXO3FCBiujCo4GU2lYO8IUPeSdurPG6e+uABzwg88d7Zt1Zuay2eleAJzqhvwU2bCOKr68wjkNw3yWRslvLAMK3vj2LPPoWYsgmLJ1YiOvPloCdD2sIVSmpLEiN5HLUteh5j6D2BUbw67a9S2TXx1J8c=
  on:
    tags: true
    repo: gregmuellegger/django-floppyforms
    condition: "$TOXENV = py35-18"
